[theme]
base = "light"           # Forces the browser to start in Light Mode logic
primaryColor = "#000000" # Makes native sliders/loaders BLACK by default
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
font = "sans serif"

[server]
headless = true